# fly.toml app configuration file generated for frontend-falling-wave-9184 on 2025-04-30T19:48:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


app = 'frontend-falling-wave-9184'
primary_region = 'yyz'

[build]


[env]
  VITE_API_URL = "https://volatilitylab-backend.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
